module.exports = {

	UNAUTHORIZED: "User not authorized .",
	OTP_SEND: 'OTP send successfully.',
	OTP_EXPIRED: 'OTP expired',
	OTP_NOT_VERIFY: 'Your account is not verified.',
	INCORRECT_OTP: 'Incorrect OTP',
	BLOCK_BY_ADMIN: 'You have been blocked by admin',
	UNBLOCK_BY_ADMIN: 'You have been unblocked by admin',
	DELETE_BY_ADMIN: 'Your account has been deleted by admin',
	NO_TOKEN: 'Please provide token',
	LOGIN: 'Login successfully',
	OTP_VERIFY: 'OTP verified successfully',
	USER_ALREADY_EXIST: 'User already exist',
	USER_NOT_FOUND: 'User not found',
	USERS_NOT_FOUND: 'Users not found',
	USERS_FOUND: 'Users found successfully.',
	CATEGORY_NOT_FOUND: 'Category not found',
	PROFILE_UPDATED: 'Profile updated successfully',
	USER_EXISTS: 'User Exists',
	MOBILE_EXIST: 'This mobile number already exists',
	EMAIL_EXIST: 'This email already exists',
	USER_DETAILS: 'User details',
	USER_CREATED: 'User created successfully',
	CATEGORY_CREATED: 'Category created successfully',
	USER_UPDATED: 'User updated successfully',
	INCORRECT_LOGIN: 'Incorrect login credential provided',
	RESET_LINK_SEND: 'Reset password link has been sent at your email.',
	PWD_CHANGED: 'Password has been changed successfully',
	PWD_NOT_MATCH: 'Password not matched.',
	UPLOAD_SUCCESS: 'File uploaded successfully',
	UPLOAD_FAILURE:'File not  upload',
	TRANSACTION_SUCCESS: 'Transaction has been completed',
	DATA_FOUND: 'Data found successfully',
	DATA_NOT_FOUND: 'Data not found',
	DETAILS_FETCHED: 'Details has been fetched successfully',
	UPDATE_SUCCESS: 'Successfully updated',
	DELETE_SUCCESS: 'Successfully deleted',
	USER_LOGOUT: 'User logged out successfully',
	PROFILE_GET: 'Fetch profile data Successfully',
	INTERNAL_ERROR: 'Internal Error',
	NOT_FOUND: 'Not Found',
	BANNER_ADDED: "Banner added successfully .",
	BANNER_UPDATED: 'Banner updated successfully',
	BLOCK_USER_EMAIL_BY_ADMIN: "This email is blocked by admin try another one.",
	BLOCK_USER_MOBILE_BY_ADMIN: "This mobile is blocked by admin try another one.",
	BLOCK_USER_BY_ADMIN: 'User has been blocked successfully.',
	UNBLOCK_USER_BY_ADMIN: 'User has been Unblocked successfully.',
	SUBSCRIPTION_LIST: 'List of plans',
    APPROVED:"Agent approved successfully .",
    REJECTED:"Agent rejected successfully .",
    SUBADMIN_ALREADY_EXIST:"SubAdmin Already Exits",
    ADMIN_NOT_FOUND:'Admin not found',
    SUBADMIN_CREATED:"SubAdmin created successfull.",
	INVALID_MODEL:"Invalid model type.",
	REGISTER_SUCCESS:"Registration successful",
	PASSWORD_NOT_MATCH:"Password and confirm password are not match",
	ALREADY_VERIFIED:"Your account is already verified",
	LOGIN_SUCCESS:"Otp send to your registered number. Please verify OTP",
	FLIGHT_BOOKED:"FlightBooked Successfully."
};
